# Generated by Django 3.0.8 on 2020-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('usn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('sem', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
